name: Releaser

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  npm:
    name: npm
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v6.0.2
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v2.1.3

      - name: Setup Pantry
        uses: home-lang/pantry/packages/action@main

      - name: Install Dependencies
        run: bun install

      - name: Publish
        run: pantry publish --npm --access public
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

      - name: Create GitHub Release
        uses: stacksjs/action-releaser@v1.2.9
        with:
          files: |
            bin/md-linux-x64.zip
            bin/md-linux-arm64.zip
            bin/md-windows-x64.zip
            bin/md-darwin-x64.zip
            bin/md-darwin-arm64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}